### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by saashqdev** [turso-extended/app-turso-crm#3]
I just did a fresh install (with the env var changes - thanks for that btw) When I run the app and try to register a tenant I get the following error:
```
AxiosError: Request failed with status code 400
    at settle (file:///home/osboxes/turso-crm/node_modules/axios/lib/core/settle.js:19:12)
    at BrotliDecompress.handleStreamEnd (file:///home/osboxes/turso-crm/node_modules/axios/lib/adapters/http.js:585:11)
    at BrotliDecompress.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
Are you able to register tenants and login etc...? The db migrations went fine and my connection seems OK. Cheers, Dave

**Comment by xinnks** [comment]
@saashqdev Let me know if changing the code [on this line](https://github.com/turso-extended/app-turso-crm/blob/master/app/lib/utils.ts#L42C6-L42C6) to `group: `${process.env.APP_GROUP}`, and adding a new env variable `APP_GROUP=default` fix your issue.

**Comment by xinnks** [comment]
@saashqdev Nice catch! Will be updating the code and blog post thanks to you.
